### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by michael-k** [jteeuwen/go-pkg-rss#62]
I want to use [Sourcegraph](https://sourcegraph.com) for go-pkg-rss code search, browsing, and usage examples. @jteeuwen, can you enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/jteeuwen/go-pkg-rss. (It should only take 30 seconds.)

Thank you!

**Comment by jteeuwen** [comment]
Is there a reason this website requires write access to commits and webhooks?

**Comment by michael-k** [comment]
Write access to commits? I don't know why they would need that.
Webhooks: I guess to get notified about changes.

**Comment by jteeuwen** [comment]
Ok, should be done now.
