### ISSUE TITLE
nil pointer dereference when *item.Guid doesn't exist.

### ISSUE THREAD

**Issue by gregf** [jteeuwen/go-pkg-rss#63]
Any time a feed is missing a guid and you call *item.Guid to retrieve it you get the following error.

```
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by michael-k** [comment]
If you want to use `*item.Guid`, you have to check first, if it's nil.
```go
if item.Guid != nil {
    // do something with *item.Guid
}
```

The better solution is to use `item.Key()` instead.

**Comment by gregf** [comment]
Thanks for the help.
